// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Comment struct {
	ID         uuid.UUID
	ParentID   uuid.NullUUID
	Commit     string
	File       null.String
	StartLine  null.Int
	EndLine    null.Int
	Body       string
	ResolvedAt null.String
	ResolvedBy null.String
	CreatedAt  string
	CreatedBy  string
}

type Commit struct {
	Sha      string
	Message  string
	Position int64
}

type Reviewer struct {
	Name       string
	CurrentSha null.String
}

type Session struct {
	BaseRef   string
	Branch    string
	CreatedAt string
}
