// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countCommits = `-- name: CountCommits :one
SELECT COUNT(*) FROM commits
`

func (q *Queries) CountCommits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllComments = `-- name: DeleteAllComments :exec
DELETE FROM comments
`

func (q *Queries) DeleteAllComments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllComments)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteCommits = `-- name: DeleteCommits :exec
DELETE FROM commits
`

func (q *Queries) DeleteCommits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCommits)
	return err
}

const deleteReviewers = `-- name: DeleteReviewers :exec
DELETE FROM reviewers
`

func (q *Queries) DeleteReviewers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteReviewers)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
`

func (q *Queries) DeleteSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSession)
	return err
}

const findCommentByPrefix = `-- name: FindCommentByPrefix :one
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE id LIKE ?||'%'
`

func (q *Queries) FindCommentByPrefix(ctx context.Context, dollar_1 sql.NullString) (Comment, error) {
	row := q.db.QueryRowContext(ctx, findCommentByPrefix, dollar_1)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Commit,
		&i.File,
		&i.StartLine,
		&i.EndLine,
		&i.Body,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const findCommitBySHAPrefix = `-- name: FindCommitBySHAPrefix :one
SELECT sha, message, position FROM commits WHERE sha LIKE ?||'%'
`

func (q *Queries) FindCommitBySHAPrefix(ctx context.Context, dollar_1 sql.NullString) (Commit, error) {
	row := q.db.QueryRowContext(ctx, findCommitBySHAPrefix, dollar_1)
	var i Commit
	err := row.Scan(&i.Sha, &i.Message, &i.Position)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Commit,
		&i.File,
		&i.StartLine,
		&i.EndLine,
		&i.Body,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getCommitByPosition = `-- name: GetCommitByPosition :one
SELECT sha, message, position FROM commits WHERE position = ?
`

func (q *Queries) GetCommitByPosition(ctx context.Context, position int64) (Commit, error) {
	row := q.db.QueryRowContext(ctx, getCommitByPosition, position)
	var i Commit
	err := row.Scan(&i.Sha, &i.Message, &i.Position)
	return i, err
}

const getCommitBySHA = `-- name: GetCommitBySHA :one
SELECT sha, message, position FROM commits WHERE sha = ?
`

func (q *Queries) GetCommitBySHA(ctx context.Context, sha string) (Commit, error) {
	row := q.db.QueryRowContext(ctx, getCommitBySHA, sha)
	var i Commit
	err := row.Scan(&i.Sha, &i.Message, &i.Position)
	return i, err
}

const getReviewer = `-- name: GetReviewer :one
SELECT name, current_sha FROM reviewers WHERE name = ?
`

func (q *Queries) GetReviewer(ctx context.Context, name string) (Reviewer, error) {
	row := q.db.QueryRowContext(ctx, getReviewer, name)
	var i Reviewer
	err := row.Scan(&i.Name, &i.CurrentSha)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT base_ref, branch, created_at FROM session LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession)
	var i Session
	err := row.Scan(&i.BaseRef, &i.Branch, &i.CreatedAt)
	return i, err
}

const insertComment = `-- name: InsertComment :exec

INSERT INTO comments (id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCommentParams struct {
	ID         uuid.UUID
	ParentID   uuid.NullUUID
	Commit     string
	File       null.String
	StartLine  null.Int
	EndLine    null.Int
	Body       string
	ResolvedAt null.String
	ResolvedBy null.String
	CreatedAt  string
	CreatedBy  string
}

// Comments
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertComment,
		arg.ID,
		arg.ParentID,
		arg.Commit,
		arg.File,
		arg.StartLine,
		arg.EndLine,
		arg.Body,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertCommit = `-- name: InsertCommit :exec

INSERT INTO commits (sha, message, position) VALUES (?, ?, ?)
`

type InsertCommitParams struct {
	Sha      string
	Message  string
	Position int64
}

// Commits
func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit, arg.Sha, arg.Message, arg.Position)
	return err
}

const insertReviewer = `-- name: InsertReviewer :exec

INSERT INTO reviewers (name, current_sha) VALUES (?, ?)
`

type InsertReviewerParams struct {
	Name       string
	CurrentSha null.String
}

// Reviewers
func (q *Queries) InsertReviewer(ctx context.Context, arg InsertReviewerParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewer, arg.Name, arg.CurrentSha)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO session (base_ref, branch, created_at) VALUES (?, ?, ?)
`

type InsertSessionParams struct {
	BaseRef   string
	Branch    string
	CreatedAt string
}

// Session
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession, arg.BaseRef, arg.Branch, arg.CreatedAt)
	return err
}

const listAllComments = `-- name: ListAllComments :many
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments
`

func (q *Queries) ListAllComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listAllComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Commit,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByCommit = `-- name: ListCommentsByCommit :many
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE "commit" = ?
`

func (q *Queries) ListCommentsByCommit(ctx context.Context, commit string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByCommit, commit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Commit,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByCreator = `-- name: ListCommentsByCreator :many
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE created_by = ?
`

func (q *Queries) ListCommentsByCreator(ctx context.Context, createdBy string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Commit,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByFile = `-- name: ListCommentsByFile :many
SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE file = ?
`

func (q *Queries) ListCommentsByFile(ctx context.Context, file null.String) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByFile, file)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Commit,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommits = `-- name: ListCommits :many
SELECT sha, message, position FROM commits ORDER BY position
`

func (q *Queries) ListCommits(ctx context.Context) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, listCommits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(&i.Sha, &i.Message, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewers = `-- name: ListReviewers :many
SELECT name, current_sha FROM reviewers
`

func (q *Queries) ListReviewers(ctx context.Context) ([]Reviewer, error) {
	rows, err := q.db.QueryContext(ctx, listReviewers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reviewer
	for rows.Next() {
		var i Reviewer
		if err := rows.Scan(&i.Name, &i.CurrentSha); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedRoots = `-- name: ListUnresolvedRoots :many

SELECT id, parent_id, "commit", file, start_line, end_line, body, resolved_at, resolved_by, created_at, created_by
FROM comments WHERE parent_id IS NULL AND resolved_at IS NULL
`

// Filtered list queries
func (q *Queries) ListUnresolvedRoots(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Commit,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reparentChildren = `-- name: ReparentChildren :exec
UPDATE comments SET parent_id = ? WHERE parent_id = ?
`

type ReparentChildrenParams struct {
	ParentID   uuid.NullUUID
	ParentID_2 uuid.NullUUID
}

func (q *Queries) ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error {
	_, err := q.db.ExecContext(ctx, reparentChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const resolveComment = `-- name: ResolveComment :exec

UPDATE comments SET resolved_at = ?, resolved_by = ? WHERE id = ? AND parent_id IS NULL
`

type ResolveCommentParams struct {
	ResolvedAt null.String
	ResolvedBy null.String
	ID         uuid.UUID
}

// Resolve
func (q *Queries) ResolveComment(ctx context.Context, arg ResolveCommentParams) error {
	_, err := q.db.ExecContext(ctx, resolveComment, arg.ResolvedAt, arg.ResolvedBy, arg.ID)
	return err
}

const sessionExists = `-- name: SessionExists :one
SELECT COUNT(*) FROM session
`

func (q *Queries) SessionExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unresolveComment = `-- name: UnresolveComment :exec
UPDATE comments SET resolved_at = NULL, resolved_by = NULL WHERE id = ?
`

func (q *Queries) UnresolveComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unresolveComment, id)
	return err
}

const updateReviewerCurrent = `-- name: UpdateReviewerCurrent :exec
UPDATE reviewers SET current_sha = ? WHERE name = ?
`

type UpdateReviewerCurrentParams struct {
	CurrentSha null.String
	Name       string
}

func (q *Queries) UpdateReviewerCurrent(ctx context.Context, arg UpdateReviewerCurrentParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewerCurrent, arg.CurrentSha, arg.Name)
	return err
}
